# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - "master"
      - "develop"
      - "feature/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-master:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
    
      - name: Instalar Dependências
        run: |
          echo "Runnnig CI MASTER!"

  ci-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
    
      - name: Instalar Dependências
        run: |
          echo "Runnnig CI DEVELOP!"

  ci-tu:
    if: contains(github.ref == 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
    
      - name: Instalar Dependências
        run: |
          echo "Runnnig CI FEATURES!"


