name: Pipeline CI Java

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: "Branch para executar o pipeline"
  
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para executar o pipeline"
        required: false
        default: "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Validar estrutura do projeto
        id: validate
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "::error::Arquivo pom.xml não encontrado!"
            exit 1
          fi

      - name: Cache de dependências Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Compilar com Maven
        run: mvn clean package -DskipTests

      - name: Executar testes
        run: mvn test

      - name: Upload de resultados de teste
        if: always()
        uses: actions/upload-artifact@v4  # Versão corrigida aqui
        with:
          name: test-results
          path: |
            **/target/surefire-reports
            **/target/failsafe-reports