name: Java CI Pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: "Branch to run the CI pipeline on"
  
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the CI pipeline on"
        required: false
        default: "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper commit hash in cache key

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'  # Automatic Maven dependency caching

      - name: Validate project structure
        id: validate
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "::error::pom.xml not found! This doesn't appear to be a Maven project."
            exit 1
          fi
          echo "Maven project detected"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Upload test results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/target/surefire-reports
            **/target/failsafe-reports