# .github/workflows/CI.yml
name: Reusable CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI
        run: |
          echo "Running CI for branch: ${{ inputs.branch }}"