name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Detect technology
      id: detect-tech
      run: |
        if [ -f "package.json" ]; then
          echo "TECHNOLOGY=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "TECHNOLOGY=python" >> $GITHUB_ENV
        elif [ -f "Gemfile" ]; then
          echo "TECHNOLOGY=ruby" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "TECHNOLOGY=java" >> $GITHUB_ENV
        else
          echo "TECHNOLOGY=unknown" >> $GITHUB_ENV
        fi

    - name: Run Node.js commands
      if: env.TECHNOLOGY == 'nodejs'
      run: |
        echo "Running Node.js commands"


    - name: Run Python commands
      if: env.TECHNOLOGY == 'python'
      run: |
        echo "Running Python commands"


    - name: Run Ruby commands
      if: env.TECHNOLOGY == 'ruby'
      run: |
        echo "Running Ruby commands"

    - name: Run Ruby commands
      if: env.TECHNOLOGY == 'java'
      run: |
        echo "Running Java Commands"

    - name: Handle unknown technology
      if: env.TECHNOLOGY == 'unknown'
      run: |
        echo "Unknown technology detected"
        exit 1