name: CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      runner:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  ci:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Dependências
        run: |
          echo "Rodando CI em: ${{ inputs.branch }}"

      - name: Executar Testes
        run: |
          echo "Rodando testes em: ${{ inputs.branch }}"

      - name: Executar Build
        run: |
          echo "Rodando build em: ${{ inputs.branch }}"
