name: CI Pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Detect technology
      id: detect-tech
      run: |
        if [ -f "package.json" ]; then
          echo "TECHNOLOGY=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "TECHNOLOGY=python" >> $GITHUB_ENV
        elif [ -f "Gemfile" ]; then
          echo "TECHNOLOGY=ruby" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "TECHNOLOGY=java" >> $GITHUB_ENV
        else
          echo "TECHNOLOGY=unknown" >> $GITHUB_ENV
        fi

    - name: Node CI
      if: env.TECHNOLOGY == 'nodejs'
      run: |
        echo "Running Node.js commands"


    - name: Python CI
      if: env.TECHNOLOGY == 'python'
      run: |
        echo "Running Python commands"


    - name: Ruby CI
      if: env.TECHNOLOGY == 'ruby'
      run: |
        echo "Running Ruby commands"

    - name: Java CI
      if: env.TECHNOLOGY == 'java'
      run: |
        echo "Iniciando compilação Java..."
        mvn clean package
        mvn test

    - name: Trata tecnologia não identificada
      if: env.TECHNOLOGY == 'unknown'
      run: |
        echo "Tecnologia não identificada"
        exit 1