name: CI Pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Detect technology
      id: detect-tech
      run: |
        if [ -f "package.json" ]; then
          echo "TECHNOLOGY=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "TECHNOLOGY=python" >> $GITHUB_ENV
        elif [ -f "Gemfile" ]; then
          echo "TECHNOLOGY=ruby" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "TECHNOLOGY=java" >> $GITHUB_ENV
        else
          echo "TECHNOLOGY=unknown" >> $GITHUB_ENV
        fi

    - name: Node CI
      if: env.TECHNOLOGY == 'nodejs'
      run: |
        echo "Running Node.js commands"
        yarn
        yarn build

    - name: Java CI
      if: env.TECHNOLOGY == 'java'
      env:
        MMS_DBSECRET: ${{ secrets.MMS_DBSECRET }}
        MMS_DBUSER: ${{ vars.MMS_DBUSER }}      
        MMS_DBURL: ${{ vars.MMS_DBURL }}
        MMS_DBAPILOGIN: ${{ vars.MMS_DBAPILOGIN}}      
      run: |
        echo "Iniciando compilação Java..."
        mvn clean package -Ddb.secret="$MMS_DBSECRET" -Ddb.user="$MMS_DBUSER" -Ddb.url="$MMS_DBURL"
        mvn test -Ddb.secret="$MMS_DBSECRET" -Ddb.user="$MMS_DBUSER" -Ddb.url="$MMS_DBURL"

    - name: Trata tecnologia não identificada
      if: env.TECHNOLOGY == 'unknown'
      run: |
        echo "Tecnologia não identificada"
        exit 1
